### ISSUE TITLE
os.Rename() error "invalid cross-device link" for Docker container with Volumes

### ISSUE THREAD

**Issue by so0k** [sethvargo/terraform-provider-filesystem#3]
When running terraform in containers this can cause errors (or even running terraform from a path on a different volume the temp directory is created on)

**Comment by so0k** [comment]
error is fixed in forked provider - https://registry.terraform.io/providers/hyphengroup/filesystem/

**Comment by sethvargo** [comment]
https://github.com/sethvargo/terraform-provider-filesystem/pull/4#issuecomment-1368282063
